# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: ellipsize
site_url: https://andgineer.github.io/ellipsize
site_author: Andrey Sorokin

# Repository
repo_name: ellipsize
repo_url: https://github.com/andgineer/ellipsize
edit_uri: edit/master/docs
docs_dir: docs

plugins:
  - awesome-pages
  - search

theme:
  name: material

extra:
  alternate:
    - name: English
      link: /ellipsize/en/
      lang: en
    - name: Russian
      link: /ellipsize/ru/
      lang: ru
