# build docs from docstrings and markdown-file in folder docs
# publish them as github pages
#
#note for myself
#
# Do not forget to set git branch `gh-pages` as source for github pages.
# This branch auto-updated by `mkdocs gh-deploy`
#
name: docs
on:
  push:
    branches:
      - main
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - run: |
          pip install -r requirements.dev.txt
          python -m pip install -e .
      - run: ./scripts/build-docs.sh
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m “mkdocs”
          git push origin gh-pages
